# Generated by Django 5.2 on 2026-04-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTechHome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Pedido',
        ),
    ]
