# Generated by Django 5.2 on 2026-04-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTechHome', '0002_rename_cliente_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_produto/'),
        ),
    ]
